baseURL = "http://example.org/"
languageCode = "en-us"
title = "Knowhere"
theme = "Knowhere"

[Params]
    mainSections = ["post","posts"]
    CustomCSS = ["css/syntax.css"]
    CustomJS = ["js/custom.js"]

[[menu.main]]
    name = "about"
    url = "/about"
    weight = 1

[markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
    noClasses = false
#    style = "github"
#pygmentsUseClasses = true
#pygentscodeFences = true